In [1]:
import cv2 as cv
import numpy as np

In [2]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

In [ ]:
cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    
    try:
        faces = classifier.detectMultiScale(img, 1.1 ,#lower the value more frames and more accuracy , 
                                            5 )#confidence value and nearest neighbours to predict value 
        for (x,y,w,h) in faces: 
            cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)
            
    
    except:
        pass
    
    
    cv.imshow('Frame'  , img )
    print(faces)
    if cv.waitKey(1) == 27:
        cam.release()
        break

[[425 279 322 322]]
[[428 277 330 330]]
[[424 277 333 333]]
[[431 278 326 326]]
[[429 277 329 329]]


2024-10-20 12:51:30.111 Python[8076:334725] +[IMKClient subclass]: chose IMKClient_Modern
2024-10-20 12:51:30.112 Python[8076:334725] +[IMKInputSession subclass]: chose IMKInputSession_Modern


[[431 280 322 322]]
[[439 281 326 326]]
[[454 280 321 321]]
[[451 287 317 317]]
[[443 285 322 322]]
[[440 292 320 320]]
[[431 297 337 337]]
[[435 285 336 336]]
[[441 274 324 324]]
[[435 271 336 336]]
[[439 276 322 322]]
[[435 272 339 339]]
[[447 269 333 333]]
[[448 274 323 323]]
[[442 271 324 324]]
[[438 270 333 333]]
[[445 271 328 328]]
[[441 269 339 339]]
[[437 269 341 341]]
[[433 271 338 338]]
[[437 267 342 342]]
[[445 275 328 328]]
[[449 270 335 335]]
[[455 274 331 331]]
[[449 270 337 337]]
[[444 269 340 340]]
[[434 269 334 334]]
[[432 269 328 328]]
[[435 273 330 330]]
[[438 272 329 329]]
[[431 260 336 336]]
[[420 262 334 334]]
[[422 269 334 334]]
[[425 274 333 333]]
[[436 274 322 322]]
[[437 276 323 323]]
[[440 280 324 324]]
[[445 285 319 319]]
[[453 288 311 311]]
[[455 291 312 312]]
[[449 290 319 319]]
[[449 289 318 318]]
[[450 292 308 308]]
[[435 287 317 317]]
[[438 291 309 309]]
[[426 278 329 329]]
[[434 283 319 319]]
[[434 283 316 316]]
[[428 275 334 334]]
[[429 278 328 328]]


In [ ]:
cam.release()