In [ ]:
import numpy as np
tpl = (1,2,3)
print(tpl)
print(type(tpl))

(1, 2, 3)
<class 'tuple'>


In [ ]:
arr = np.array(tpl)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
lst = [1,2,3]
print(lst)
print(type(lst))
print('-'*10)

arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
----------
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
dct = {1 : 'apple', 2 : 'banana', 3 : 'cherry'}
print(dct)
print(type(dct))
print('-'*10)

arr = np.array(dct)
print(arr)
print(type(arr))
print('-'*10)

{1: 'apple', 2: 'banana', 3: 'cherry'}
<class 'dict'>
----------
{1: 'apple', 2: 'banana', 3: 'cherry'}
<class 'numpy.ndarray'>
----------


In [ ]:
arr_k = np.array(list(dct.keys()))
arr_v = np.array(list(dct.values()))
print(arr_k)
print(type(arr_k))
print(arr_v)
print(type(arr_v))

[1 2 3]
<class 'numpy.ndarray'>
['apple' 'banana' 'cherry']
<class 'numpy.ndarray'>


In [11]:
import numpy as np
set_ = {1,2,3}
print(set_)
print(type(set_))
print('-'*10)

arr = np.array(list(set_))
print(arr)
print(type(arr))

{1, 2, 3}
<class 'set'>
----------
[1 2 3]
<class 'numpy.ndarray'>


In [13]:
# Converting a String to an Array:

import numpy as np
arr = np.array(list('hello world'))
print(arr)
print(type(arr))


['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>
