In [1]:
import numpy as np
B = np.array([[1,2,3], [4,5,6], [7,8,9]])
determinant = np.linalg.det(B)
print(determinant)

0.0


In [2]:
import numpy as np
A = np.array([[1,2],[3,4]])
determinant = np.linalg.det(A)
print(determinant)

-2.0000000000000004


In [3]:
import numpy as np
B = np.array([[1,2,3], [4,5,6], [7,8,9]])
Transpose = np.transpose(B)
print(Transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
import numpy as np
A = np.array([[1,2],[3,4]])
Inverse = np.linalg.inv(A)
print(Inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]
