In [1]:
import numpy as np
a = np.array([1, 2])
b = np.array([2, 3])
dot_product = np.dot(a, b)

In [2]:
print("Dot Product:", dot_product)

Dot Product: 8


In [3]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
product = np.matmul(A, B)
print("Matrix Product:\n", product)

Matrix Product:
 [[10 13]
 [22 29]]


In [4]:
import numpy as np
C = np.array([1, 2])
D = np.array([[4, 1], [3, 5]])
product = np.matmul(C, D)
print("Broadcasted Matrix Product:\n", product)

Broadcasted Matrix Product:
 [10 11]


In [5]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
product_dot = np.dot(A, B)
product_matmul = np.matmul(A, B)
print("Dot Product:\n", product_dot)
print("Matrix Multiplication:\n", product_matmul)

Dot Product:
 [[10 13]
 [22 29]]
Matrix Multiplication:
 [[10 13]
 [22 29]]
