In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,20,size=(5,5))
print(arr[arr>5])


[ 6  8 11 10  6 18  7 15 14 10 17  8 18  9 13 13 17 18 16 10 18 14]


In [15]:
print(arr[arr%2==0])
print(arr[(arr%2==0) & (arr>5)])
print(arr[(arr%3==0) | (arr%7==0)])

[ 2  8  2  4  4  8  2  2  4 10  8]
[ 8  8 10  8]
[9 7 7 9 3 7 3]


In [17]:
import numpy as np
arr = np.random.randint(1,11,size=(5,5))
arr1 = np.array([True, False, True,False,True])
print(arr[arr1])
print(arr)


[[ 8  8  4  7  5]
 [ 1  9  7  6 10]
 [ 3 10 10 10  7]]
[[ 8  8  4  7  5]
 [ 7  9  6  6  7]
 [ 1  9  7  6 10]
 [ 7  2  7  2  3]
 [ 3 10 10 10  7]]


In [18]:
import numpy as np
arr = np.random.randint(1,11,size=(5,5))
filtered_arr = arr[2][arr[2,:] > 5]
print(filtered_arr)

[6]


In [19]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

15
21
[5 7 9]
[ 6 15]


In [20]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


In [21]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.std(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

1.4142135623730951
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [23]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.min(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

print('-'*20)

arr = np.array([1,2,3,4,5])
print(np.max(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))
# column wise filtering

1
1
[1 2 3]
[1 4]
--------------------
5
6
[4 5 6]
[3 6]
