In [16]:
lst = [1,2,3,4,5]
print(lst)
lst1 = lst
print(lst1)
print('-'*10)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------


In [17]:
lst[0] = 5
print(lst)
print(lst1)
print('-'*10)

lst1[0] = 4
print(lst)
print(lst1)

[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
----------
[4, 2, 3, 4, 5]
[4, 2, 3, 4, 5]


In [18]:
print()
print('*'*20)
print()

lst = [1,2,3,4,5]
print(lst)
lst1 = lst.copy()
print(lst1)
print('-'*10)



lst[0] = 5
print(lst)
print(lst1)
print('-'*10)
lst[0] = 1

lst1[0] = 5
print(lst)
print(lst1)


********************

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[1, 2, 3, 4, 5]
[5, 2, 3, 4, 5]


In [19]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr_ = arr.copy()
print(arr)
print(arr_)

[1 2 3 4 5]
[1 2 3 4 5]


In [20]:
my_list = [1, 2, 3, 4, 5]
print(my_list[0])
print(my_list[-1])
print(my_list[2])
print(my_list[1:4])
print(my_list[:3])
print(my_list[3:])
print(my_list[::2])
print(my_list[::-1])

1
5
3
[2, 3, 4]
[1, 2, 3]
[4, 5]
[1, 3, 5]
[5, 4, 3, 2, 1]


In [21]:
my_list[0] = 10
print(my_list)

del my_list[1]
print(my_list)

[10, 2, 3, 4, 5]
[10, 3, 4, 5]


In [22]:
my_list[1:1] = [20, 30]
print(my_list)

[10, 20, 30, 3, 4, 5]


In [23]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])

print(my_array[0])
print(my_array[-1])
print(my_array[2])

1
5
3


In [24]:
my_array[0] = 10
print(my_array)

np.delete(my_array, 1)
print(my_array)

[10  2  3  4  5]
[10  2  3  4  5]


In [25]:
np.insert(my_array, 1, [20, 30])
print(my_array)

[10  2  3  4  5]


In [26]:
import numpy as np
zeros_array = np.zeros(10)
print(zeros_array)
print('-----')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----
