In [1]:
import numpy as np
lst = [1,3,2]
print(lst)
print(type(lst))
print('---')

arr = np.array([1,2,3])
print(arr)
print(type(arr))
print('---')

[1, 3, 2]
<class 'list'>
---
[1 2 3]
<class 'numpy.ndarray'>
---


In [4]:
print(arr == lst)
print(arr.tolist() == lst)

[ True False False]
False


In [5]:
print(sorted(arr) == sorted(lst))

True


In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
import numpy as np
arr = np.array([(1,2,3),(4,5,6)])
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [10]:
import numpy as np
arr = np.array([{'a' : 1, 'b' : 2, 'c' : 3},{'d' : 4, 'e' : 5, 'f' : 6}])
print(arr)


[{'a': 1, 'b': 2, 'c': 3} {'d': 4, 'e': 5, 'f': 6}]


In [11]:
import numpy as np
arr = np.array([[1,1],[4,1],[2,3]])
print(arr.shape)

(3, 2)


In [13]:
import numpy as np
arr = np.array([[1,1,1],[4,1,1],[2,3,1]])
print(arr.ndim)

2


In [14]:
import numpy as np
arr = np.array([[1,1,2,2],[2,3,2,1]])
print(type(arr))

<class 'numpy.ndarray'>
