In [1]:
import numpy as np
zeros_array = np.zeros(10)
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 4))
print(zeros_array)
print('-----')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----


In [2]:
zeros_array = np.zeros((2, 3, 4))
print(zeros_array)
print('-----')


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----


In [3]:
import numpy as np
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
ones_array = np.ones((2, 3), dtype = int)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [9]:
import numpy as np
eye_array = np.eye(3,4)
print(eye_array)
print('-----')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----


In [10]:
import numpy as np
print(np.random.rand())
print(np.random.rand(10))
print(np.random.rand(3, 3))

0.16019891698097177
[0.20003027 0.07009639 0.29819704 0.12155206 0.46419315 0.35725457
 0.18443793 0.41895296 0.80916514 0.54252414]
[[0.70550699 0.34305953 0.2933542 ]
 [0.13161239 0.68068934 0.26202947]
 [0.29549189 0.8085697  0.91953392]]


In [11]:
print(np.random.randint(100, size=10))
print(np.random.randint(100, size=(3, 3)))

[71 59 70 98 20 42 46 64  3  7]
[[ 9 97 31]
 [19 49 34]
 [59 70 32]]


In [13]:
print(np.random.uniform(size=(3, 3))) #uniform distribution between 0 and 1

[[0.74979542 0.87391198 0.16079072]
 [0.6774535  0.70230953 0.6902776 ]
 [0.51294876 0.11630362 0.34117703]]


In [15]:
print(np.random.binomial(10, 0.5, size=(3, 3))) #binomial distribution with n=10 and p=0.5

[[4 4 2]
 [4 5 5]
 [6 3 5]]
