In [7]:
import numpy as np
data = np.loadtxt('data.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
import numpy as np
data = np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


In [17]:
import numpy as np

data = np.loadtxt('data.csv', delimiter=',')
print(data)


[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
import numpy as np
data = np.loadtxt('datajson.json', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]
