In [5]:
import numpy as np
#linear search
arr = np.array([1,3,4,6,5,7,12,13])
index = np.where(arr == 3)[0]
print(index)

[1]


In [11]:
#binary search
arr = np.array([1,3,4,6,5,7,12,13])
index = np.searchsorted(arr, 3)
print(index)


1


In [12]:

arr = np.array([1,3,4,5,6,7,12,13])
index = np.searchsorted(arr, 6)
print(index)


4


In [13]:
arr = np.array([1,3,4,6,5,7,12,13])
index = np.argmin(abs(arr - 11))
print(index)

6


In [14]:
arr = np.array([5,7,9,0,3,1,6,2,4,8])
sorted_arr = np.sort(arr)
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
sorted_arr = np.sort(arr, kind = 'quicksort') #by default
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
sorted_arr = np.sort(arr, kind = 'heapsort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
sorted_arr = np.sort(arr, kind = 'mergesort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]
